export enum ParticipationStatusEnumerator {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CHECKIN = 'CHECKIN',
    CHECKOUT = 'CHECKOUT',
    CERTIFICATE_GENERATED = 'CERTIFICATE_GENERATED',
    CERTIFICATE_SENT = 'CERTIFICATE_SENT',
    CERTIFICATE_REVOKED = 'CERTIFICATE_REVOKED',
    CERTIFICATE_APPROVED = 'CERTIFICATE_APPROVED',
}